services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - BUCKET_NAME=bucket
      - BUCKET_HOST=http://fake-gcs-server:4443
      - GOOGLE_APPLICATION_CREDENTIALS=/app/test/credentials.json
    depends_on:
      - fake-gcs-server

  fake-gcs-server:
    image: fsouza/fake-gcs-server
    command: "-scheme http"
    ports:
      - "4443:4443"
    volumes:
      - "${PWD}/test/dist:/data/bucket"

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - BUCKET_NAME=bucket
      - BUCKET_HOST=http://fake-gcs-server:4443
      - GOOGLE_APPLICATION_CREDENTIALS=/app/test/credentials.json
    command: npm test
    depends_on:
      - app
      - fake-gcs-server