name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run tests with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d
        docker-compose -f docker-compose.yml run --rm tests
        docker-compose -f docker-compose.yml down
    
    - name: Get the current date
      id: date
      run: echo "::set-output name=date::$(date +%s)"
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: jamesmtc
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64 --file Dockerfile --tag jamesmtc/gin_proxy:${{ steps.date.outputs.date }} --tag jamesmtc/gin_proxy:latest .
    
    - name: Push the Docker image
      run: docker push jamesmtc/gin_proxy --all-tags